<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport"  content="width=device-width, initial-scale=1.0">
<meta name="author"  content="burak">
<title>HTML Homework</title>
</head>
<body>
<h1>WP 2019-Hafta 02-Ödev</h1>
<p>Bu haftaki derste daha fazla<mark>HTML Attribüt</mark>erini tanidik ve biraz daha detaylarina baktik ve<mark>HTML entitels</mark>`ler ile-<br>tanisdik.Ayrica <strong><U>Form </U></strong>ve kullanicilarin bilgi girebilmesi icin <strong><u>input</u></strong> elemanlarini tanidik. Asagida "Hafta 04 konsept-<BR>ler ve linkler" bölümünde bu hafta istediklerimizi özet olarak bulabilirsiniz.</p>


 <h3><mark><strong>HATIRLATMA</strong></mark></h3>
  <details><strong>Teori derslerinde gordügünuz disinda kendinizde ayrica arastirma yapip tag ve attributlrti ögreniniz. </strong><br><br> Ölcu olarak, alttaki dagilimi referans alabilirsiniz:<ul><li>%25 Teori</li><li>%20 Pratik</li><li>%25 Ödev</li><li>%30 Kendi basiniza arastirma</li></ul><summary><font color=#E90808>OKU BENI!!!</font></summary></details>

  <h3>Hafta 04 konseptler ve linkler</h3>

<details><summary>Göster...</summary><ul><li><strong>HTML Taglari</strong></li><ul><li>form/input/select/textarea/label/button/fieldset/legend<li>audio,progress,meter,textarea,video,map,select,option<li>meta<li>meta tag kullanim örnekleri<a href=https://gist.github.com/kevinSuttle/1997924>https://gist.github.com/kevinSuttle/1997924</a><li>embed,iframe<li>Daha fazlasi:<a href=https://html.com/tags/>https://html.com/tags</a></li></ul><li><strong>HTML Attribütleri</strong> <ul><li>Global</li><li>id,class,title,style,data,hidden,lang,tabindex,contenteditable</li><li>event handlers</li>
 <li>onlick,onfocus,onchange,onmouseout,onmouseover,ondblclick</li><li>daha fazlasi:<a href=https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference>Dev Mozilla Reference</a></li>
<li>Tag spesifik</li><li>src,alt,href,target,type,auto focus,auto complete,place holder
    <li>pattern,place holder,min,max,size,minlenght,maxlength,name,readonly,required,<br>spellcheck,value</li><li>loop,autoplay,muted played,buffered</li><li>Teori slaytlarina ve html.com/attributes`a kullanim kontextleri ve daha fazlasi icin bakiniz.</li>
   </li><li>daha fazlasi:<a href=https://www.w3schools.com/html/html_attributes.asp>html attributes</a></li></ul></li>


 <strong><li>HTML entytiy`leri</li></strong><ul><li><p> &#128513;,&#129315;,&#128169;,&#128584;,&#128526;</p></li><li>Karakter referans sayfasi:<a href="https://www.w3schools.com/charsets/ref_emoji.asp">HTML Entities Interactive Reference </a></li>
 </ul> </details>




   
   <div align="center"><p> <table border="1" >        <div align="center"><p><em>Isvicre`de bazi kanlonlar ile ilgili bilgiler</em></p> </div>   
    <tr>
           <th bgcolor=#15ABAD> Isim</th> 
            <th bgcolor=#15ABAD >kisaltma</th> 
            <th  bgcolor=#15ABAD>en büyük sehri</th>
            <th  bgcolor=#15ABAD>nüfusu</th> 
            <th  bgcolor=#15ABAD>konusulan dil</th> 
            <th  bgcolor=#15ABAD>bayragi</th> 
            <th  bgcolor=#15ABAD>sayfasi</th>
        </tr>
    <tr>
          <td>Zurich</td>
          <td>ZH</td>
          <td>Zürich</td>
          <td>1`504`346</td>
          <td>almanca</td>
          <td><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Wappen_Z%C3%BCrich_matt.svg/800px-Wappen_Z%C3%BCrich_matt.svg.png" height=20 height=20></td>
          <td><a href=https://www.zh.ch/internet/de/home.html>zh.ch</a></td>
        </tr>
        <tr>
            <td>Genevre</td>
            <td>GE</td>
            <td>Cenevre</td>
            <td>495`249</td>
            <td>Fransizca</td>
            <td><img id="product-collection-image-38827" src="https://www.kellerfahnen.ch/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/1/6/16133-1_2.jpg" length=20 width="20" alt="16133-1.jpg"></td>
            <td><a href=https://www.ge.ch>ge.ch</a></td>
        </tr>
        <tr>
            <td>Bern</td>
            <td>BE</td>
            <td>Bern</td>
            <td>1`031`126</td>  
            <td>Fransizca,almanca</td>
            <td><img src="http://www.tell.ch/schweiz/kanton/genf.png"  length=20 width="20" border="0" alt="[Bild: genf.png]"></td>
            <td><a href=https://www.be.ch/>be.ch</a></td>
        </tr>
  </table>
    <table border="1" >
             <tr> 
               <th bgcolor=#F9F91A>Toplam nüfus</th>  
             <td>  8`039`060  </td> </tr>  
  </table></p> </div>   
</body>
</html>
